### ISSUE TITLE
Switch to flat badges by default

### ISSUE THREAD

**Issue by mgedmin** [badges/pypipins#34]
shields.io recently had a [flag day](https://github.com/badges/shields/issues/185#issuecomment-65898604) and [switched](https://github.com/badges/shields/commit/f2319a2d482f74cca56e7d139d7878369a73b0d4) the default badge style to flat.

It'd be awesome if PyPI Pin would do the same.  Uneven badges don't look very nice.

**Comment by kura** [comment]
I could do it, I've held off on doing it because when I've done this in the past it's been met with users being unhappy.

**Comment by mgedmin** [comment]
Yeah, I was rather unhappy when Travis unilaterally switched their badge style to flat.  My unhappiness was mostly caused by the badges being inconsistent with everything else.  But now it looks like everything else is switching to the new flat badge style.

I hope any residual user unhappiness can be mitigated by documenting the style switch and providing an option to keep the old style (`?style=plastic` works with shields.io and some other badge services).
