### ISSUE TITLE
python versions are listed multiple times in the badges

### ISSUE THREAD

**Issue by ssbarnea** [badges/pypipins#36]
Please take a look at https://pypi.python.org/pypi/jira and you will see that some python versions are duplicated, like 2.6 and 2.7 ones. 

I was not able to find any reason why this would happen.

**Comment by jhermann** [comment]
Look at your Trove list in setup, and you know why.

**Comment by jhermann** [comment]
PS: Of course, and improvement for `pypipins` would be a strategically placed `sorted(set(…))`.
