### ISSUE TITLE
Seems dead again

### ISSUE THREAD

**Issue by harlowja** [badges/pypipins#38]
The following seems to be dead https://pypip.in/version/kazoo/badge.svg ? 

Something up? Other? Dead again :crying_cat_face:

**Comment by harlowja** [comment]
I get a `504 Gateway Time-out` btw after a while...

**Comment by kura** [comment]
Looks fine to me. I'll have a look in the logs but I didn't receive any alerts due to backend services being down.

**Comment by harlowja** [comment]
Agreed, seems maybe it was a temporary thing. Closing.
